public class Constants {

    public static final Integer HTTP_STATUS_NOT_FOUND = 404;

    public static final String HEADER_CONTENT_TYPE = 'Content-Type';
    public static final String HEADER_CONTENT_DISPOSITION = 'Content-Disposition';
    public static final String CONTENT_TYPE_APPLICATION_JSON = 'application/json';
    
    public static final String STATUS_COMPLETE = 'Complete';
    public static final String STATUS_INCOMPLETE = 'Incomplete';
        
    public static final String IMAGE = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAA' +
                                         'DElEQVQImWNITU0FAAJiATCoYcVSAAAAAElFTkSuQmCC';
    
    public static final String Image_2 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAAXNSR0IArs4c6QAAAARnQU1BAACx' +
											'jwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAMSURBVBhXY/j//z8ABf4C/qc1gYQAAAAASUVORK5CYII=';
    
    public static final String LIST_OF_CARDS_PAGE = 'https://c.eu9.visual.force.com/apex/CardsListPage';
    public static final String NEW_CARD_PAGE = 'https://c.eu9.visual.force.com/apex/NewCardPage';

    public static final String FIELD_ID = 'Id';
    public static final String FIELD_STATUS = 'status';
        
}